# 异常处理

#### 概念：
我们的代码在运行时出现错误需要解决的时候，就需要将错误信息传达给某个接受者处理，而这个接受者就是异常处理机制，它会负责处理这个问题，这就是异常处理。（个人见解）

#### 基本异常：
一般有一下意料之外的事情发生了，而你不知道该怎么处理，这个时候就会使用throw关键字（throws关键字进行异常说明）抛出异常，异常抛出后，有发生以下几件事情：

- a、在堆上创建异常对象，终止当前执行路径。
- b、从当前环境中弹出异常对象的引用。
- c、异常处理机制接管程序，从异常处理程序位置继续执行程序。

我们使用try关键字来捕捉异常，具体语法如下：
	
	try{//语句}
然后处理异常的程序可以使用关键字catch，具体语法如下：
	
```java

	try{
		//语句
	}catch(Type1 id1){
		;//语句
	}catch(Type2 id2){
		;//语句
	}

```

另外我们还可以编写自己的异常类并且使用，如下所示：
	
```java

	class MyException extends Exception{
		MyException(){};
		MyException(String msg){super(msg);}
	}
	public class Main{
		public static void f()throws MyException{
			System.out.println("在f()中抛出异常！");
			throw new MyException("在f()中");
		}
		public static void main(String[] args){
			try{
				f();
			}catch(MyException e){
				e.printStackTrace(System.out);
			}
		}
	}
	/*output:
	在f()中抛出异常！
	MyException: 在f()中
        at Main.f(Main.java:8)
        at Main.main(Main.java:12)
	*/
	这里也可以使用Logger打印日志

```

另外对于Error，Exception和RuntimeException我们可以使用带有cause的构造器把原始抛出的异常保存下来，而没有带参数cause的类我们可以使用initCause()方法来保存原始异常，然后抛出一个新的异常，即把先抛出的异常插入到后抛出的异常之中！
（这一点非常有用，我们可以使用不需要抛出被检查的异常的RuntimeException来包装其他的被检查的异常如：IOException，然后再在其他地方使用getCause()来提取包装的异常进行处理）


#### finally进行清理

finlly语句原型如下（finally子句总是会执行）：

```java

	try{
		//语句1
	}catch(Type1 id1){
		;//语句2
	}finally{
		;//语句3
	}

```

无论语句1是否捕获异常，语句3都会被执行，我们一般可以使用finally在进行一些收尾的工作，比如关掉某些打开的输入输出流。

要注意一个问题：使用finally关键字的时候我们可能把异常忽略掉了，如（并不会有任何输出，这个一个缺陷）：

```java

    try{
    	throw new RuntimeException();
    }finally{
    	return ;
   	}

```

对于构造器会抛出异常的类，我们要是用finally谨慎处理！